version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  postgresql:
    image: postgres:13
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - 'postgres_data_backups:/backups'
    env_file:
      - enviroment/environment
#    ports:
#      - '5433:5432'

  django:
    image: django-template:dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - '.:/opt/project'
    env_file:
      - enviroment/environment
    depends_on:
      - makemigrations
      - migrate
#      - redis
    links:
      - postgresql
#      - redis
    ports:
      - '8000:8000'

  makemigrations:
    image: django-template:dev
    command: python3 manage.py makemigrations
    volumes:
      - '.:/opt/project'
    env_file:
      - enviroment/environment
    depends_on:
      - postgresql
    links:
      - postgresql

  migrate:
    image: django-template:dev
    command: python3 manage.py migrate
    volumes:
      - '.:/opt/project'
    env_file:
      - enviroment/environment
    depends_on:
      - makemigrations
      - postgresql
    links:
      - postgresql

#  redis:
#    image: redis:latest